hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${task.name}-${algo.name}${suffix}
  job:
    chdir: true

headless: true
suffix: ""
exp_name: ${oc.select:task.name,test}-${oc.select:algo.name,none}${suffix}

app:
  headless: ${..headless}
  enable_cameras: ${..eval_render}

# total_frames: 300_000_000
total_frames: 150_000_000
eval_render: false
save_interval: 300
seed: 0
checkpoint_path: null
vecnorm: ${oc.select:algo.vecnorm,train}

camera_follow: true

wandb:
  name: ${..exp_name}/${now:%m-%d}_${now:%H-%M}
  job_type: train
  project: hdmi
  mode: online # set to 'disabled' when debugging locally
  tags: []

defaults:
  - task: G1/G1Track-walk
  - algo: ppo
  - _self_
