# @package task
# G1 机器人 TWIST 运动跟踪任务配置文件
# 这个文件是使用从 TWIST 转换的运动数据进行训练的模板配置

# 继承基础配置
defaults:
  - base/hdmi-base  # 继承 HDMI 基础配置
  - _self_          # 当前文件的配置

# 任务名称：G1 TWIST 运动跟踪
name: G1TrackTwistMotion

# 可视化设置
viewer:
  lookat: [0., 0., 0.5]  # 相机注视点
  eye: [2., 2., 2.]      # 相机位置：等距视角

# 任务特定配置
max_episode_length: 1000  # 根据你的运动数据长度调整

# 机器人配置 - G1 人形机器人
robot:
  name: g1
  # 注意：robot_type 需要根据你的任务调整
  # 如果只做运动跟踪（不需要操作物体），使用简化版本：
  robot_type: g1_29dof_rubberhand  # 29自由度，橡胶手
  # 如果需要操作物体，使用带物体配置的版本：
  # robot_type: g1_29dof_rubberhand-feet_sphere-eef_box-body_capsule

# 命令配置 - TWIST 运动跟踪任务
command:
  # !!!! 重要：修改为你转换后的 TWIST 数据路径 !!!!
  data_path: data/motion/g1/twist_converted  # 从 TWIST 转换的运动数据目录

  # 如果只有部分子文件夹需要训练，可以使用正则表达式：
  # data_path: data/motion/g1/twist_converted/(mocap_0|mocap_1|mocap_2)

  root_body_name: "pelvis"  # 根身体名称：骨盆

  # ===== 如果你的任务不需要物体交互，请删除或注释以下部分 =====
  # 物体配置（根据你的任务调整或删除）
  # object_asset_name: "suitcase"
  # object_body_name: "suitcase"

  # 接触目标位置偏移（如果没有物体交互，删除此部分）
  # contact_target_pos_offset:
  #   - [-0.1, 0.18, 0.25]
  #   - [-0.1,-0.18, 0.25]

  # 末端执行器位置偏移（如果没有物体交互，删除此部分）
  # contact_eef_pos_offset:
  #   - [0.05, 0.0, 0.0]
  #   - [0.05, 0.0, 0.0]
  # ===== 物体配置结束 =====

# ===== 如果你的任务是纯运动跟踪（无物体），需要修改以下配置 =====
# 修改命令类型为 RobotTracking（不需要物体跟踪）
command:
  _target_: active_adaptation.envs.mdp.commands.hdmi.command.RobotTracking
  data_path: data/motion/g1/twist_converted
  root_body_name: "pelvis"

  # 跟踪关键点名称（与 hdmi-base.yaml 相同）
  tracking_keypoint_names: [
    ".*_hip_(pitch|yaw)_link",
    ".*_knee_link",
    ".*_ankle_roll_link",
    "pelvis",
    "torso_link",
    ".*_shoulder_pitch_link",
    ".*_elbow_link",
    ".*_wrist_yaw_link"
  ]

  # 跟踪关节名称
  tracking_joint_names: [
      "waist_.*_joint",
      ".*_hip_.*_joint",
      ".*_knee_joint",
      ".*_ankle_.*_joint",
      ".*_shoulder_.*_joint",
      ".*_elbow_joint"
  ]

  # 姿态和速度随机化范围（与 hdmi-base.yaml 相同）
  pose_range:
    x: [-0.05, 0.05]
    y: [-0.05, 0.05]
    z: [-0.01, 0.01]
    roll: [-0.1, 0.1]
    pitch: [-0.1, 0.1]
    yaw: [-0.2, 0.2]

  velocity_range:
    x: [-0.2, 0.2]
    y: [-0.2, 0.2]
    z: [-0.2, 0.2]
    roll: [-0.5, 0.5]
    pitch: [-0.5, 0.5]
    yaw: [-0.5, 0.5]

  init_joint_pos_noise: 0.1
  init_joint_vel_noise: 0.1

  future_steps: [1, 2, 8, 16, 32]

# ===== 观察配置调整（如果无物体交互） =====
# 如果是纯运动跟踪，需要移除物体相关的观察
observation:
  # 命令观察（保持不变）
  command:
    ref_body_pos_future_local: {}
    ref_joint_pos_future: {}
    ref_motion_phase: {}

  # 策略观察（保持不变）
  policy:
    root_ang_vel_history: {history_steps: [0], noise_std: 0.05}
    projected_gravity_history: {history_steps: [0], noise_std: 0.05}
    joint_pos_history: {history_steps: [0, 1, 2, 3, 4, 8], noise_std: 0.015}
    prev_actions: {steps: 3}

  # ===== 如果无物体交互，删除 object 和 depth 部分 =====
  # object: {}
  # depth: {}

  # 特权观察（保持不变）
  priv:
    root_ang_vel_history: {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}
    projected_gravity_history: {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}
    joint_pos_history: {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}

    ref_root_pos_future_b: {}
    ref_root_ori_future_b: {}

    diff_body_pos_future_local: {}
    diff_body_ori_future_local: {}
    diff_body_lin_vel_future_local: {}
    diff_body_ang_vel_future_local: {}

    root_linvel_b: {}
    body_pos_b: {body_names: ".*ankle_roll_link"}
    body_vel_b: {body_names: ".*ankle_roll_link"}
    body_height: {body_names: [".*ankle_roll_link", "pelvis", "torso_link"]}

    applied_action: {}
    applied_torque: {}

    # ===== 如果无物体交互，删除以下物体相关观察 =====
    # object_pos_b: {}
    # object_ori_b: {}
    # diff_object_pos_future: {}
    # diff_object_ori_future: {}
    # ref_object_contact_future: {}
    # diff_contact_pos_b: {}

# ===== 奖励配置调整（如果无物体交互） =====
reward:
  # 跟踪奖励组（保持不变 - 这是主要的运动跟踪奖励）
  tracking:
    tracking_upper_body_pos(keypoint_pos_tracking_local_product):
      body_names: [".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]
      weight: 0.5
      sigma: 0.5

    tracking_upper_body_ori(keypoint_ori_tracking_local_product):
      body_names: [".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]
      weight: 0.5
      sigma: 1.0

    tracking_lower_body_pos(keypoint_pos_tracking_local_product):
      body_names: [".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link"]
      weight: 0.5
      sigma: 0.5

    tracking_lower_body_ori(keypoint_ori_tracking_local_product):
      body_names: [".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link"]
      weight: 0.5
      sigma: 1.0

    tracking_root_pos(keypoint_pos_tracking_product):
      body_names: ["pelvis"]
      weight: 0.5
      sigma: 0.5

    tracking_root_ori(keypoint_ori_tracking_product):
      body_names: ["pelvis"]
      weight: 0.5
      sigma: 0.5

    tracking_body_linvel(keypoint_lin_vel_tracking_product):
      body_names: ["pelvis", ".*_hip_yaw_link", ".*_knee_link", ".*_ankle_roll_link", "torso_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]
      weight: 0.5
      sigma: 0.5

    tracking_body_angvel(keypoint_ang_vel_tracking_product):
      body_names: ["pelvis", ".*_hip_yaw_link", ".*_knee_link", ".*_ankle_roll_link", "torso_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]
      weight: 0.5
      sigma: 2.5

    joint_pos_tracking_product:
      joint_names: ["waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"]
      weight: 0.5
      sigma: 0.25

    joint_vel_tracking_product:
      joint_names: ["waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"]
      weight: 0.5
      sigma: 2.5

  # ===== 如果无物体交互，删除 object_tracking 组 =====
  # object_tracking: {}

  # 运动奖励组（保持不变）
  loco:
    action_rate_l2: {weight: 0.1, enabled: true}
    joint_vel_l2: {weight: 5.0e-4, enabled: true, joint_names: .*}
    joint_pos_limits: {weight: 10.0, joint_names: ".*", soft_factor: 0.9, enabled: true}
    joint_torque_limits: {weight: 0.01, enabled: true, soft_factor: 0.6}
    survival: {weight: 1.0, enabled: true}

  # 足部奖励组（保持不变）
  feet:
    impact_force_l2: {weight: 1.0, enabled: true, body_names: .*ankle_roll_link}
    feet_slip: {weight: 0.5, tolerance: 0.0, enabled: true, body_names: .*ankle_roll_link}
    feet_air_time: {weight: 5.0, enabled: true, body_names: .*ankle_roll_link, thres: 0.5, soft_discount: 1.0}
    survival: {weight: 1.0, enabled: true}

# ===== 终止条件调整（如果无物体交互） =====
termination:
  # 累积身体位置误差终止
  cum_body_pos_error: {body_names: "torso_link", min_steps: 25, threshold: 0.5}
  cum_body_ori_error: {body_names: "torso_link", min_steps: 25, threshold: 1.2}

  # 累积身体位置误差终止（局部坐标系）
  cum_body_pos_error_local: {body_names: ".*", min_steps: 25, threshold: 0.5}
  cum_body_ori_error_local: {body_names: ".*", min_steps: 25, threshold: 1.2}

  # ===== 如果无物体交互，删除以下物体相关终止条件 =====
  # cum_object_pos_error: {min_steps: 25, threshold: 0.5}
  # cum_object_ori_error: {min_steps: 25, threshold: 0.8}
  # cum_lost_contact_steps: {min_steps: 25, pos_thres: 0.2, frc_thres: 1.0}

# 随机化配置（根据需要调整）
randomization:
  # 身体质量扰动
  perturb_body_mass:
    .*: [0.9, 1.1]

  # 身体材料属性扰动
  perturb_body_materials:
    body_names: [".*ankle_roll_link", ".*_wrist_yaw_link"]
    static_friction_range: [0.3, 1.6]
    dynamic_friction_range: [0.3, 1.2]
    restitution_range: [0.0, 0.2]

  # 身体质心扰动
  perturb_body_com:
    body_names: ["pelvis", "torso_link"]
    com_range: [-0.02, 0.02]

  # 关节偏移扰动
  random_joint_offset:
    .*: [-0.01, 0.01]

  # ===== 如果无物体交互，删除以下物体相关随机化 =====
  # object_body_randomization: {}
  # body_scale: {}
