# @package task
# HDMI (Humanoid Dynamic Motion Imitation) 基础任务配置文件
# 这个文件定义了人形机器人动态运动模仿任务的基础配置
# 包含环境设置、机器人配置、观察、奖励、随机化等所有必要参数

# 任务名称 - 必须在具体任务中重写 (例如: G1TrackSuitcase)
name: ???

# 可视化设置
viewer:
  resolution: [2560, 1440]  # 渲染分辨率 [宽度, 高度]
  lookat: [0., 0., 0.]      # 相机注视点 [x, y, z]
  eye: [4.0, 4.0, 4.0]      # 相机位置 [x, y, z]
  env_spacing: 3.0          # 环境实例之间的间距

# 地形设置
terrain: plane              # 地形类型：平面

# 环境配置
num_envs: 4096              # 并行环境数量
max_episode_length: 1000    # 最大回合长度（步数）

# 仿真设置
sim:
  step_dt: 0.02              # 环境步长时间 (秒)
  isaac_physics_dt: 0.005    # Isaac Lab 物理步长时间 (秒)
  mujoco_physics_dt: 0.002   # MuJoCo 物理步长时间 (秒)

# 机器人配置
robot:
  name: ???                  # 机器人名称 - 必须在具体任务中重写
  robot_type: ???            # 机器人类型 - 必须在具体任务中重写

# 动作配置
action:
  _target_: active_adaptation.envs.mdp.action.JointPosition  # 动作类型：关节位置控制
  
  # 动作缩放因子 - 控制各关节的动作幅度
  action_scaling:
    .*_hip_yaw_joint: 0.55        # 髋关节偏航
    .*_hip_roll_joint: 0.35       # 髋关节横滚
    .*_hip_pitch_joint: 0.55      # 髋关节俯仰
    .*_knee_joint: 0.35           # 膝关节
    .*_ankle_pitch_joint: 0.44    # 踝关节俯仰
    .*_ankle_roll_joint: 0.44     # 踝关节横滚
    waist_roll_joint: 0.44        # 腰部横滚
    waist_pitch_joint: 0.44       # 腰部俯仰
    waist_yaw_joint: 0.55         # 腰部偏航
    .*_shoulder_pitch_joint: 0.44 # 肩关节俯仰
    .*_shoulder_roll_joint: 0.44  # 肩关节横滚
    .*_shoulder_yaw_joint: 0.44   # 肩关节偏航
    .*_elbow_joint: 0.44          # 肘关节
    # .*_wrist_roll_joint: 0.44   # 腕关节横滚 (已注释)
    # .*_wrist_pitch_joint: 0.07  # 腕关节俯仰 (已注释)
    # .*_wrist_yaw_joint: 0.07    # 腕关节偏航 (已注释)
  
  min_delay: 2                    # 最小动作延迟 (步数)
  max_delay: 6                    # 最大动作延迟 (步数)
  alpha: [0.8, 1.0]              # 动作平滑参数范围

# 命令配置 - 机器人-物体跟踪任务
command:
  _target_: active_adaptation.envs.mdp.commands.hdmi.command.RobotObjectTracking
  data_path: ???             # 数据路径 - 必须在具体任务中重写

  # 跟踪关键点名称 - 用于运动跟踪的机器人身体部位
  tracking_keypoint_names: [
    ".*_hip_(pitch|yaw)_link",   # 髋关节链接
    ".*_knee_link",              # 膝关节链接
    ".*_ankle_roll_link",        # 踝关节链接
    "pelvis",                    # 骨盆
    "torso_link",                # 躯干链接
    ".*_shoulder_pitch_link",    # 肩关节链接
    ".*_elbow_link",             # 肘关节链接
    ".*_wrist_yaw_link"          # 腕关节链接
  ]

  # 跟踪关节名称 - 用于运动跟踪的关节
  tracking_joint_names: [
      "waist_.*_joint",          # 腰部关节
      ".*_hip_.*_joint",         # 髋关节
      ".*_knee_joint",           # 膝关节
      ".*_ankle_.*_joint",       # 踝关节
      ".*_shoulder_.*_joint",    # 肩关节
      ".*_elbow_joint"           # 肘关节
  ]

  root_body_name: ???           # 根身体名称 - 必须在具体任务中重写

  # 机器人姿态范围 - 用于随机化初始姿态
  pose_range:
    x: [-0.05, 0.05]         # X轴位置范围 (米)
    y: [-0.05, 0.05]         # Y轴位置范围 (米)
    z: [-0.01, 0.01]         # Z轴位置范围 (米)
    roll: [-0.1, 0.1]        # 横滚角范围 (弧度)
    pitch: [-0.1, 0.1]       # 俯仰角范围 (弧度)
    yaw: [-0.2, 0.2]         # 偏航角范围 (弧度)

  # 机器人速度范围 - 用于随机化初始速度
  velocity_range:
    x: [-0.2, 0.2]           # X轴速度范围 (米/秒)
    y: [-0.2, 0.2]           # Y轴速度范围 (米/秒)
    z: [-0.2, 0.2]           # Z轴速度范围 (米/秒)
    roll: [-0.5, 0.5]        # 横滚角速度范围 (弧度/秒)
    pitch: [-0.5, 0.5]       # 俯仰角速度范围 (弧度/秒)
    yaw: [-0.5, 0.5]         # 偏航角速度范围 (弧度/秒)

  init_joint_pos_noise: 0.1  # 初始关节位置噪声标准差
  init_joint_vel_noise: 0.1  # 初始关节速度噪声标准差

  future_steps: [1, 2, 8, 16, 32]  # 未来步数 - 用于预测

  extra_object_names: []     # 额外物体名称列表
  
  # 用于跟踪的物体
  object_asset_name: ???     # 物体资产名称 - 必须在具体任务中重写 (例如: "suitcase")
  object_body_name: ???      # 物体身体名称 - 必须在具体任务中重写 (例如: "suitcase")

  # 物体姿态范围 - 用于随机化物体初始姿态
  object_pose_range:
    x: [-0.05, 0.05]         # 物体X轴位置范围 (米)
    y: [-0.05, 0.05]         # 物体Y轴位置范围 (米)
    z: [-0.01, 0.01]         # 物体Z轴位置范围 (米)
    roll: [-0.1, 0.1]        # 物体横滚角范围 (弧度)
    pitch: [-0.1, 0.1]       # 物体俯仰角范围 (弧度)
    yaw: [-0.1, 0.1]         # 物体偏航角范围 (弧度)

  contact_target_pos_offset: ??? # 接触目标位置偏移 - 必须在具体任务中重写
  contact_eef_body_name: ["left_wrist_yaw_link", "right_wrist_yaw_link"]  # 末端执行器身体名称
  contact_eef_pos_offset:    # 末端执行器位置偏移
    - [0.0, 0.0, 0.0]        # 左手腕偏移
    - [0.0, 0.0, 0.0]        # 右手腕偏移

# 相机设置
enable_cameras: false        # 是否启用相机
camera_width: 160            # 相机宽度 (像素)
camera_height: 120           # 相机高度 (像素)
# 观察配置 - 定义智能体可以观察到的信息
observation:
  # 命令观察 - 来自参考运动的命令信息
  command:
    ref_body_pos_future_local: {}  # 参考身体未来位置 (局部坐标系)
    ref_joint_pos_future:      {}  # 参考关节未来位置
    ref_motion_phase:          {}  # 参考运动相位
  
  # 策略观察 - 用于策略网络的观察
  policy:
    root_ang_vel_history:      {history_steps: [0], noise_std: 0.05}  # 根部角速度历史
    projected_gravity_history: {history_steps: [0], noise_std: 0.05}  # 投影重力历史
    joint_pos_history:         {history_steps: [0, 1, 2, 3, 4, 8], noise_std: 0.015}  # 关节位置历史
    prev_actions:              {steps: 3}  # 历史动作

  # 物体观察 - 关于跟踪物体的信息
  object:
    object_xy_b:               {noise_std: 0.01, episodic_noise_std: 0.0}  # 物体XY位置 (身体坐标系)
    object_heading_b:          {noise_std: 0.01, episodic_noise_std: 0.0}  # 物体朝向 (身体坐标系)
    ref_contact_pos_b:         {noise_std: 0.01, episodic_noise_std: 0.02, yaw_only: true}  # 参考接触位置
  depth:
    depth_camera:              {camera_name: "tiled_camera"}  # 深度相机

  # 特权观察 - 用于训练但不用于推理的观察 (无噪声)
  priv:
    root_ang_vel_history:      {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}  # 根部角速度历史
    projected_gravity_history: {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}  # 投影重力历史
    joint_pos_history:         {history_steps: [0, 1, 2, 3, 4, 5, 6, 7, 8], noise_std: 0.0}  # 关节位置历史

    ref_root_pos_future_b: {}  # 参考根部未来位置 (身体坐标系)
    ref_root_ori_future_b: {}  # 参考根部未来朝向 (身体坐标系)

    diff_body_pos_future_local: {}  # 身体位置未来差异 (局部坐标系)
    diff_body_ori_future_local: {}  # 身体朝向未来差异 (局部坐标系)
    diff_body_lin_vel_future_local: {}  # 身体线速度未来差异 (局部坐标系)
    diff_body_ang_vel_future_local: {}  # 身体角速度未来差异 (局部坐标系)

    root_linvel_b:    {}  # 根部线速度 (身体坐标系)
    body_pos_b:       {body_names: ".*ankle_roll_link"}  # 身体位置 (踝关节)
    body_vel_b:       {body_names: ".*ankle_roll_link"}  # 身体速度 (踝关节)
    body_height:      {body_names: [".*ankle_roll_link", "pelvis", "torso_link"]}  # 身体高度

    applied_action:   {}  # 应用的动作
    applied_torque:   {}  # 应用的扭矩 export ANTHROPIC_AUTH_TOKEN="cr_63a41d77d1168b1352ffa555ffb1ddb3a06a045393a6d885b1a67d25504ee2d8"

    object_pos_b:     {}  # 物体位置 (身体坐标系)
    object_ori_b:     {}  # 物体朝向 (身体坐标系)
    diff_object_pos_future: {}  # 物体位置未来差异
    diff_object_ori_future: {}  # 物体朝向未来差异

    ref_object_contact_future: {}  # 参考物体接触未来
    diff_contact_pos_b:        {}  # 接触位置差异 (身体坐标系)

  # 参考关节位置观察
  ref_joint_pos_:
    ref_joint_pos_action_policy: {}  # 参考关节位置动作策略

# 奖励配置 - 定义强化学习的奖励函数
reward:
  # 跟踪奖励组 - 鼓励机器人跟踪参考运动
  tracking:
    # 上半身位置跟踪
    tracking_upper_body_pos(keypoint_pos_tracking_local_product):
      body_names: [".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]  # 肩、肘、腕关节
      weight: 0.5  # 奖励权重
      sigma: 0.5   # 高斯奖励的标准差
    
    # 上半身朝向跟踪
    tracking_upper_body_ori(keypoint_ori_tracking_local_product):
      body_names: [".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]
      weight: 0.5
      sigma: 1.0

    # 下半身位置跟踪
    tracking_lower_body_pos(keypoint_pos_tracking_local_product):
      body_names: [".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link"]  # 髋、膝、踝关节
      weight: 0.5
      sigma: 0.5
    
    # 下半身朝向跟踪
    tracking_lower_body_ori(keypoint_ori_tracking_local_product):
      body_names: [".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link"]
      weight: 0.5
      sigma: 1.0

    # 根部位置跟踪
    tracking_root_pos(keypoint_pos_tracking_product):
      body_names: ["pelvis"]  # 骨盆
      weight: 0.5
      sigma: 0.5
    
    # 根部朝向跟踪
    tracking_root_ori(keypoint_ori_tracking_product):
      body_names: ["pelvis"]
      weight: 0.5
      sigma: 0.5

    # 身体线速度跟踪
    tracking_body_linvel(keypoint_lin_vel_tracking_product):
      body_names: ["pelvis", ".*_hip_yaw_link", ".*_knee_link", ".*_ankle_roll_link", "torso_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]
      weight: 0.5
      sigma: 0.5
    
    # 身体角速度跟踪
    tracking_body_angvel(keypoint_ang_vel_tracking_product):
      body_names: ["pelvis", ".*_hip_yaw_link", ".*_knee_link", ".*_ankle_roll_link", "torso_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"]
      weight: 0.5
      sigma: 2.5

    # 关节位置跟踪
    joint_pos_tracking_product:
      joint_names: ["waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"]
      weight: 0.5
      sigma: 0.25
    
    # 关节速度跟踪
    joint_vel_tracking_product:
      joint_names: ["waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"]
      weight: 0.5
      sigma: 2.5
  # 物体跟踪奖励组 - 鼓励机器人跟踪和操作物体
  object_tracking:
    # _multiplicative: true  # 乘性奖励组合 (已注释)
    object_pos_tracking: {weight: 1.0, sigma: 0.5}  # 物体位置跟踪
    object_ori_tracking: {weight: 1.0, sigma: 0.5}  # 物体朝向跟踪
    eef_contact_exp:     {weight: 1.0, enabled: true, pos_sigma: 0.3, frc_sigma: 40.0, frc_thres: 10.0, gain: 5.0}  # 末端执行器接触奖励
  
  # 运动奖励组 - 鼓励稳定的运动模式
  loco:
    action_rate_l2:     {weight: 0.1, enabled: true}  # 动作变化率L2惩罚
    joint_vel_l2:       {weight: 5.0e-4, enabled: true, joint_names: .*}  # 关节速度L2惩罚
    joint_pos_limits:   {weight: 10.0, joint_names: ".*", soft_factor: 0.9, enabled: true}  # 关节位置限制
    joint_torque_limits: {weight: 0.01, enabled: true, soft_factor: 0.6}  # 关节扭矩限制
    survival:           {weight: 1.0, enabled: true}  # 生存奖励
  
  # 足部奖励组 - 鼓励正确的足部行为
  feet:
    impact_force_l2:    {weight: 1.0, enabled: true, body_names: .*ankle_roll_link}  # 冲击力L2惩罚
    feet_slip:          {weight: 0.5, tolerance: 0.0, enabled: true, body_names: .*ankle_roll_link}  # 足部滑动惩罚
    feet_air_time:      {weight: 5.0, enabled: true, body_names: .*ankle_roll_link, thres: 0.5, soft_discount: 1.0}  # 足部空中时间
    survival:           {weight: 1.0, enabled: true}  # 生存奖励
  # 调试奖励组 - 用于调试和监控 (默认禁用)
  debug:
    feet_air_time:      {weight: 5.0, enabled: false, body_names: .*ankle_roll_link, thres: 0.2, soft_discount: 1.0}  # 足部空中时间
    feet_contact_count: {weight: 1.0, enabled: false, body_names: .*ankle_roll_link}  # 足部接触计数
    joint_pos_limits:   {weight: 1.0, enabled: false, soft_factor: 0.9, joint_names: .*}  # 关节位置限制
    eef_contact_all:    {weight: 1.0, enabled: false, frc_thres: 1.0, pos_thres: 0.1}  # 末端执行器接触
    root_pos_error(keypoint_pos_error):             {body_names: ["pelvis"], weight: 1.0, enabled: false}  # 根部位置误差
    root_ori_error(keypoint_ori_error):             {body_names: ["pelvis"], weight: 1.0, enabled: false}  # 根部朝向误差
    body_pos_error_local(keypoint_pos_error_local): {body_names: [".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"], weight: 1.0, enabled: false}  # 身体位置误差 (局部)
    body_ori_error_local(keypoint_ori_error_local): {body_names: [".*_hip_pitch_link", ".*_knee_link", ".*_ankle_roll_link", ".*_shoulder_pitch_link", ".*_elbow_link", ".*_wrist_yaw_link"], weight: 1.0, enabled: false}  # 身体朝向误差 (局部)
    joint_pos_error:             {joint_names: ["waist_.*_joint", ".*_hip_.*_joint", ".*_knee_joint", ".*_shoulder_.*_joint", ".*_elbow_joint"], weight: 1.0, enabled: false}  # 关节位置误差

# 随机化配置 - 用于域随机化，提高策略的鲁棒性
randomization:
  # 身体质量扰动
  perturb_body_mass:
    .*: [0.9, 1.1]  # 所有身体部位的质量在90%-110%之间随机变化 python scripts/smplx_to_robot_dataset.py --src_folder /home/ubuntu/DATA2/Dataset-G1 --tgt_folder /home/ubuntu/DATA2/Dataset-G1/AMASS_RETARGET --robot unitree_g1 --num_cpus 60

  
  # 身体材料属性扰动
  perturb_body_materials:
    body_names: [".*ankle_roll_link", ".*_wrist_yaw_link"]  # 踝关节和腕关节
    static_friction_range: [0.3, 1.6]    # 静摩擦系数范围
    dynamic_friction_range: [0.3, 1.2]   # 动摩擦系数范围
    restitution_range: [0.0, 0.2]        # 恢复系数范围
  
  # 身体质心扰动
  perturb_body_com:
    body_names: ["pelvis", "torso_link"]  # 骨盆和躯干
    com_range: [-0.02, 0.02]             # 质心偏移范围 (米)
  
  # 关节偏移扰动
  random_joint_offset:
    .*: [-0.01, 0.01]  # 所有关节的偏移范围 (弧度)

# 终止条件配置 - 定义何时结束回合
termination:
  # 累积身体位置误差终止
  cum_body_pos_error:       {body_names: "torso_link",  min_steps: 25, threshold: 0.5}  # 躯干位置误差超过0.5米
  cum_body_ori_error:       {body_names: "torso_link",  min_steps: 25, threshold: 1.2}  # 躯干朝向误差超过1.2弧度

  # 累积身体位置误差终止 (局部坐标系)
  cum_body_pos_error_local: {body_names: ".*",  min_steps: 25, threshold: 0.5}  # 任何身体部位位置误差超过0.5米
  cum_body_ori_error_local: {body_names: ".*",  min_steps: 25, threshold: 1.2}  # 任何身体部位朝向误差超过1.2弧度

  # 累积物体位置误差终止
  cum_object_pos_error:     {min_steps: 25, threshold: 0.5}  # 物体位置误差超过0.5米
  cum_object_ori_error:     {min_steps: 25, threshold: 0.8}  # 物体朝向误差超过0.8弧度

  # 累积失去接触步数终止
  cum_lost_contact_steps:   {min_steps: 25, pos_thres: 0.2, frc_thres: 1.0}  # 失去接触超过阈值
